variables-one:
	mkdir -p contracts
	cp ../src/contracts/Variables.sol contracts/
	npx hardhat test test_variables.js --grep 'step 1'

variables-two:
	mkdir -p contracts
	cp ../src/contracts/Variables.sol contracts/
	npx hardhat test test_variables.js --grep 'step 2'

variables-three:
	mkdir -p contracts
	cp ../src/contracts/Variables.sol contracts/
	npx hardhat test test_variables.js --grep 'step 3'

variables-four:
	mkdir -p contracts
	cp ../src/contracts/Variables.sol contracts/
	npx hardhat test test_variables.js --grep 'step 4'

datatypes-one:
	mkdir -p contracts
	cp ../src/contracts/DataTypes.sol contracts/
	npx hardhat test test_dataTypes.js --grep 'step 1'

datatypes-two:
	mkdir -p contracts
	cp ../src/contracts/DataTypes.sol contracts/
	npx hardhat test test_dataTypes.js --grep 'step 2'

datatypes-three:
	mkdir -p contracts
	cp ../src/contracts/DataTypes.sol contracts/
	npx hardhat test test_dataTypes.js --grep 'step 3'

datastructures-one:
	mkdir -p contracts
	cp ../src/contracts/DataStructures.sol contracts/
	npx hardhat test test_dataStructures.js --grep 'step 1'

datastructures-two:
	mkdir -p contracts
	cp ../src/contracts/DataStructures.sol contracts/
	npx hardhat test test_dataStructures.js --grep 'step 2'

datastructures-three:
	mkdir -p contracts
	cp ../src/contracts/DataStructures.sol contracts/
	npx hardhat test test_dataStructures.js --grep 'step 3'

datastructures-four:
	mkdir -p contracts
	cp ../src/contracts/DataStructures.sol contracts/
	npx hardhat test test_dataStructures.js --grep 'step 4'

datastructures-five:
	mkdir -p contracts
	cp ../src/contracts/DataStructures.sol contracts/
	npx hardhat test test_dataStructures.js --grep 'step 6'

functions-one:
	mkdir -p contracts
	cp ../src/contracts/Functions.sol contracts/
	npx hardhat test test_functions.js --grep 'step 1'

functions-two:
	mkdir -p contracts
	cp ../src/contracts/Functions.sol contracts/
	npx hardhat test test_functions.js --grep 'step 2'

functions-three:
	mkdir -p contracts
	cp ../src/contracts/Functions.sol contracts/
	npx hardhat test test_functions.js --grep 'step 3'

functions-four:
	mkdir -p contracts
	cp ../src/contracts/Functions.sol contracts/
	npx hardhat test test_functions.js --grep 'step 4'

controlstructures-one:
	mkdir -p contracts
	cp ../src/contracts/ControlStructures.sol contracts/
	npx hardhat test test_controlStructures.js --grep 'step 1'

controlstructures-two:
	mkdir -p contracts
	cp ../src/contracts/ControlStructures.sol contracts/
	npx hardhat test test_controlStructures.js --grep 'step 2'

controlstructures-three:
	mkdir -p contracts
	cp ../src/contracts/ControlStructures.sol contracts/
	npx hardhat test test_controlStructures.js --grep 'step 3'

controlstructures-four:
	mkdir -p contracts
	cp ../src/contracts/ControlStructures.sol contracts/
	npx hardhat test test_controlStructures.js --grep 'step 4'

controlstructures-five:
	mkdir -p contracts
	cp ../src/contracts/ControlStructures.sol contracts/
	npx hardhat test test_controlStructures.js --grep 'step 5'

controlstructures-six:
	mkdir -p contracts
	cp ../src/contracts/ControlStructures.sol contracts/
	npx hardhat test test_controlStructures.js --grep 'step 6'

controlstructures-seven:
	mkdir -p contracts
	cp ../src/contracts/ControlStructures.sol contracts/
	npx hardhat test test_controlStructures.js --grep 'step 7'