variables-one:
	mkdir -p contracts
	cp ../src/contracts/Variables.sol contracts/
	npx hardhat test test_variables.js --grep 'step 1'

variables-two:
	mkdir -p contracts
	cp ../src/contracts/Variables.sol contracts/
	npx hardhat test test_variables.js --grep 'step 2'

variables-three:
	mkdir -p contracts
	cp ../src/contracts/Variables.sol contracts/
	npx hardhat test test_variables.js --grep 'step 3'

variables-four:
	mkdir -p contracts
	cp ../src/contracts/Variables.sol contracts/
	npx hardhat test test_variables.js --grep 'step 4'