one:
	mkdir -p contracts
	cp ../src/contracts/Variables.sol contracts/
	npx hardhat test test_variables.js

two:
	mkdir -p contracts
	cp ../src/contracts/DataTypes.sol contracts/
	npx hardhat test test_dataTypes.js

three:
	mkdir -p contracts
	cp ../src/contracts/DataStructures.sol contracts/
	npx hardhat test test_dataStructures.js

four:
	mkdir -p contracts
	cp ../src/contracts/Functions.sol contracts/
	npx hardhat test test_functions.js

five:
	mkdir -p contracts
	cp ../src/contracts/ControlStructures.sol contracts/
	npx hardhat test test_controlStructures.js