version: '3.9'
services:
  content:
    build: .
    networks: 
      - lab
    image: labs-playground
    volumes:
      - src-volume:/root/lab/src
  workspace:
    depends_on:
      - content
    networks: 
      - lab
    # image: ca-py-image:latest
    image: 421805900968.dkr.ecr.us-east-2.amazonaws.com/cloudacademy/labs-workspace/ca-theia-express-node-18v2:latest     
    ports: 
      - "3000:3000"
    volumes:
      - src-volume:/home/project
volumes:
  src-volume:

networks:
  lab: